name 'settings'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures settings'
long_description 'Installs/Configures settings'
version '0.1.0'
